### ISSUE TITLE
Host on GitHub pages

### ISSUE THREAD

**Issue by mckelveygreg** [Smacherman/myPersonalEmojis#1]
Head to your settings and turn on GitHub pages so it can be hosted!

**Comment by Smacherman** [comment]
@mckelveygreg So I turned them on, but it doesn't seem like my page exists yet? Is there another place I need to enable it? :S

**Comment by mckelveygreg** [comment]
Nice! It looked like this worked!! How long did it take it to come up? I'm having my own issues publishing currently

**Comment by Smacherman** [comment]
@mckelveygreg  to be honest... I didn't realize it was working! But finally figured out how it works with the URL (https://smacherman.github.io/myPersonalEmojis/). 

Yours looks like it's redirecting well to http://www.mckelveygreg.com/! Awesome page btw!! Gotta make something similar. 👯‍♂️
